import { businessVerticals as cmsVerticals } from "./generated/businessVerticals";
import { metrics as cmsMetrics } from "./generated/metrics";
import { publicationSettings as cmsPublication } from "./generated/publicationSettings";
import type { CompanyMetric } from "./homepage";

/**
 * Business — The Operating Manual.
 * Sixth major NDR editorial publication.
 *
 * Phase 2B — the operating divisions flow from the CMS-managed
 * `business-verticals` collection (regenerated byte-identically into
 * `./generated/businessVerticals`), the masthead as-on/edition line from the
 * `publication-settings` collection, and each division's proof-metric
 * references resolve against the shared `metrics` ledger (§11.3) via the
 * frozen `VERTICAL_PROOF_METRIC_KEYS` index. Editorial copy that has no CMS
 * counterpart — the chapter architecture, masthead statement, capability
 * matrix, corporate structure, capital deployment and execution frameworks —
 * stays frozen.
 */

export type Chapter = {
  index: string;
  label: string;
  id: string;
  title: string;
  plate: string;
  code: string;
};

/**
 * The four chapters of the shipped manual, numbered in rendered order.
 *
 * The Business page renders exactly four numbered chapters:
 *
 *   01 · Operating Verticals
 *   02 · Execution
 *   03 · Integrated Business Model
 *   04 · Corporate Structure
 *
 * The unrendered Business V1 chapters (02 Capabilities & Services and
 * 04 Capital Deployment) are intentionally absent from the chapter of
 * record — they are not revived and carry no visible numbering.
 */

export const businessChapters = [
  {
    index: "01",
    label: "Operating Verticals",
    id: "verticals",
    title: "What the company runs.",
    plate: "PL. 101",
    code: "OP.01",
  },
  {
    index: "02",
    label: "Execution",
    id: "execution",
    title: "How projects are delivered.",
    plate: "PL. 201",
    code: "OP.02",
  },
  {
    index: "03",
    label: "Integrated Business Model",
    id: "business-model-title",
    title: "How capital flows.",
    plate: "PL. 301",
    code: "OP.03",
  },
  {
    index: "04",
    label: "Corporate Structure",
    id: "structure",
    title: "How the corporate body is assembled.",
    plate: "PL. 401",
    code: "OP.04",
  },
] as const satisfies readonly Chapter[];

export const verticalsChapter = businessChapters[0];
export const executionChapter = businessChapters[1];
export const integratedBusinessModelChapter = businessChapters[2];
export const corporateStructureChapter = businessChapters[3];

export const businessMasthead = {
  folio: "OP. MANUAL · FY26",
  controlCaption: "Cover · Sheet 01 of 06",
  asOn: cmsPublication.asOnDate,
  edition: `Edition ${cmsPublication.editionPeriod} · Volume I`,
  statement:
    "Developing, owning and managing high-quality industrial, commercial and institutional assets for over 60 years.",
  headline: { before: "The ", accent: "operating", after: " manual." },
} as const;

/**
 * Vertical 02 renders a heading-only masthead: the eyebrow and the as-on/
 * edition meta line are removed (the `VerticalPage` `isV2` branch) and the h1
 * falls back to the division's full title.
 */

/**
 * Per-vertical overview heading rendered above the overview description.
 * `emphasis` lists phrases within the description that are set off in the
 * rendered copy.
 */
export const verticalOverview: Readonly<
  Record<string, { heading: string; emphasis?: readonly string[] }>
> = {
  "01": {
    heading: "Building infrastructure that moves businesses forward",
  },
  "02": {
    heading: "Building assets. Managing execution. Delivering performance.",
    emphasis: [
      "construction and development of industrial and logistics assets",
      "delivered on time, within budget, to the required quality, and ready for operations",
    ],
  },
  "03": {
    heading: "Creating well-planned communities for better living.",
  },
};

export type DivisionSpecRow = { label: string; value: string };

export type DivisionRoute = { label: string; href: string; external?: boolean };

export type DivisionProofMetric = { key: string; name: string; value: string };

export type Division = {
  index: string;
  title: string;
  writeup: string;
  spec: readonly DivisionSpecRow[];
  proof: string;
  proofSource: string;
  route: DivisionRoute;
  source: string;
  anchor?: string;
  metrics: readonly DivisionProofMetric[];
};

/**
 * Proof-metric references per vertical, keyed by vertical index. Each key
 * resolves against the published Metrics ledger (§11.3); the figure lives once
 * in the ledger and the vertical references it rather than duplicating it.
 * The `metrics` field on the CMS `business-verticals` records is seeded from
 * this index and the parity layer verifies the two stay in step.
 */
export const VERTICAL_PROOF_METRIC_KEYS: Readonly<Record<string, readonly string[]>> = {
  "01": ["M14"],
  "02": [],
  "03": [],
};

type CmsVerticalRecord = {
  id: string;
  index: string;
  title: string;
  writeup: string;
  proof: string;
  proofSource: string;
  anchor?: string;
  source: string;
  spec: readonly { label: string; value: string }[];
  route: { label: string; href: string; external?: boolean };
  metrics: readonly { metricKey?: string }[];
};

const cmsVerticalData = cmsVerticals as unknown as readonly CmsVerticalRecord[];

const cmsDivisions: readonly Division[] = cmsVerticalData.map((record) => ({
  index: record.index,
  title: record.title,
  writeup: record.writeup,
  spec: record.spec.map((row) => ({ label: row.label, value: row.value })),
  proof: record.proof,
  proofSource: record.proofSource,
  ...(record.anchor !== undefined ? { anchor: record.anchor } : {}),
  route: {
    label: record.route.label,
    href: record.route.href,
    ...(record.route.external === true ? { external: true } : {}),
  },
  source: record.source,
  metrics: record.metrics
    .map(({ metricKey }) => cmsMetrics.find((metric) => metric.key === metricKey))
    .filter((metric): metric is (typeof cmsMetrics)[number] => metric !== undefined)
    .map((metric) => ({ key: metric.key, name: metric.name, value: metric.value })),
}));

export const divisions: readonly Division[] = cmsDivisions;

export const capabilityMatrix = {
  footprint: {
    label: "Operating footprint",
    line: "Mumbai · NCR · Bengaluru · Chennai · Kolkata · Pune · Goa · Hyderabad · Surat",
    note: "access to ~80% of India's consumption markets",
    source: "Source: NDR Corporate Presentation",
  },
  headers: ["Capability", "Scope", "Evidence"] as const,
  rows: [
    {
      phase: "ORIGINATION",
      capability: "SPV funding",
      scope: "Financial assistance to group SPVs for land acquisition and construction",
      evidence: "Subsidiaries / JVs",
    },
    {
      phase: "DEVELOPMENT",
      capability: "Development & delivery",
      scope: "Conceptualization, design and delivery of institutional-grade assets",
      evidence: "6,00,000 sq ft delivered in 4 months",
    },
    {
      phase: "DEVELOPMENT",
      capability: "Project management",
      scope:
        "Design coordination, procurement, scheduling, construction management, quality assurance, timely completion",
      evidence: "100%-owned project management arm",
    },
    {
      phase: "DEVELOPMENT",
      capability: "Plotting & land development",
      scope: "Planning, plotting, approvals, marketing and sale of RERA-compliant layouts",
      evidence: "Ave Acres · aveacres.com",
    },
    {
      phase: "OPERATIONS",
      capability: "Operations & asset management",
      scope:
        "Facility & property management, maintenance planning, statutory compliance, tenant coordination, HSE",
      evidence: "98% portfolio occupancy",
    },
    {
      phase: "TRANSFER",
      capability: "Asset transfer",
      scope: "Sale or transfer of SPVs, including offers to NDR InvIT under ROFO",
      evidence: "INR 143.9 cr MLG transfer",
    },
  ] as const,
  source: "Source: Client IA response · Post-Demerger business note · NDR Corporate Presentation",
} as const;

export type StructureBranch = {
  name: string;
  function: string;
  relationship: string;
  route?: DivisionRoute;
  routeNote?: string;
};

export const corporateStructure = {
  header: { name: "NDR Smart Spaces Pvt. Ltd.", role: "Parent platform of the NDR Group" },
  branches: [
    {
      name: "Group SPVs",
      function: "Owns / leases land · constructs warehouses",
      relationship: "Rental income · subsidiaries / JVs",
      routeNote: "Asset register routes to Portfolio when built",
    },
    {
      name: "NDR Asset Management Pvt. Ltd.",
      function: "Project management company",
      relationship: "Ownership · project management",
    },
    {
      name: "Ave Acres LLP",
      function: "Development entity · plotting",
      relationship: "Development fee · sale of developed land",
      route: { label: "Ave Acres", href: "https://aveacres.com", external: true },
    },
    {
      name: "NDR InvIT Trust",
      function: "Separate listed entity under the NDR Group",
      relationship: "Sale of SPV ownership · consideration",
      route: { label: "NDR InvIT Trust", href: "https://ndrinvit.com", external: true },
    },
    {
      name: "Third parties",
      function: "Sale of developed land",
      relationship: "Consideration",
    },
  ] as readonly StructureBranch[],
  source: "Source: NDR structure diagram · Post-Demerger business note",
} as const;

export type ChainNode = { index: string; name: string; caption: string };

export const capitalDeployment = {
  rofo: "Right of First Offer — NDR InvIT evaluates each eligible asset before any third party.",
  chain: [
    { index: "01", name: "Develop", caption: "SPVs build on owned or leased land" },
    {
      index: "02",
      name: "Offer under ROFO",
      caption: "Each eligible asset is offered before any third party",
    },
    { index: "03", name: "Transfer", caption: "SPV ownership transfers to NDR InvIT" },
    { index: "04", name: "Recycle", caption: "Consideration returns to new development" },
    { index: "05", name: "Develop", caption: "The loop begins again" },
  ] as const satisfies readonly ChainNode[],
  evidence: "INR 143.9 cr MLG transfer · SPV transfers to NDR InvIT",
  evidenceSource: "Source: NDR Corporate Presentation",
  cta: { label: "NDR InvIT Trust", href: "https://ndrinvit.com" },
  source: "Source: Client IA response · NDR Corporate Presentation",
} as const;

export const execution = {
  evidenceLabel: "Execution record",
  chain: [
    { index: "01", name: "Originate", caption: "Identify land and structure the SPV" },
    { index: "02", name: "Design", caption: "Design coordination and scheduling" },
    { index: "03", name: "Procure", caption: "Procurement of materials and services" },
    { index: "04", name: "Build", caption: "Construction management and quality assurance" },
    {
      index: "05",
      name: "Assure & Deliver",
      caption: "Inspection, assurance and timely completion",
    },
    { index: "06", name: "Operate", caption: "Facility and asset management" },
  ] as const satisfies readonly ChainNode[],
  evidence: [
    {
      claim: "6,00,000 sq ft Amazon Fulfilment Centre delivered in 4 months",
      source: "Source: NDR Corporate Presentation",
    },
    {
      claim: "99% of industrial projects of NDR are greenfield",
      source: "Source: NDR Corporate Presentation",
    },
  ] as const,
  source: "Source: Client IA response · NDR Corporate Presentation",
} as const;

export const businessClosing = {
  line: "How the platform runs, documented.",
  enquiry: { label: "Business Enquiry", href: "mailto:project@ndrsmart.com" },
  portfolio: {
    label: "View the asset portfolio",
    note: "Opens with the Portfolio page · Phase 2",
  },
} as const;

/**
 * Vertical 02 — Project and Operations Management Consultancy - NDR Asset
 * Management. Figures are configurable and flow through the count-up
 * treatment (`Vertical02Stats`). "Projects in Pipeline" remains a 999
 * scaffold — no client figure has been supplied for it yet.
 */
export const vertical02Metrics: readonly (Omit<CompanyMetric, "value"> & { value: number })[] = [
  {
    value: 10,
    suffix: " Mn Sq. Ft.",
    label: "Asset under construction",
    context: "Asset under construction",
  },
  { value: 230, label: "Strength of the team", context: "Strength of the team" },
  { value: 999, label: "Projects in Pipeline", context: "Projects in Pipeline" },
];

export type AssetPerformanceFunction = { index: string; title: string };

/**
 * Vertical 02 subpage — Asset Performance Management. Editorial copy is
 * frozen; the four function slots ship titled "Function 1"–"Function 4"
 * pending the client's service documentation, and the three stats are
 * configurable counters (999 scaffold) flowing through `CompanyMetrics`.
 */
export const vertical02AssetManagement = {
  intro: {
    heading: "Keeping assets productive. Keeping businesses moving.",
    description:
      "We manage the leasing and ongoing maintenance of industrial and logistics assets, ensuring facilities deliver consistent performance throughout their operational lifecycle. Our approach combines tenant management, facility upkeep, preventive maintenance, repairs, and operational support to maintain asset quality, tenant satisfaction, safety, and long-term value.",
  },
  functions: [
    { index: "01", title: "Function 1" },
    { index: "02", title: "Function 2" },
    { index: "03", title: "Function 3" },
    { index: "04", title: "Function 4" },
  ] as const satisfies ReadonlyArray<AssetPerformanceFunction>,
  placeholderNote: "Function scope pending documentation.",
  metrics: [
    { value: 98, suffix: "%", label: "Occupancy Status", context: "Occupancy Status" },
    {
      value: 33,
      suffix: " Mn Sq. Ft.",
      label: "Asset Under Management",
      context: "Asset Under Management",
    },
    // No locations figure has been supplied yet — shown as text, not a count-up.
    { value: null, label: "Pending", context: "Locations" },
  ] as const satisfies ReadonlyArray<CompanyMetric>,
  cta: {
    eyebrow: "Business Enquiry",
    heading: "Looking for the Right Space for Your Business?",
    body: "Explore our available industrial and logistics facilities or speak to our team about your requirements.",
    note: "We typically respond within 2 business days. For investor-specific queries, write to compliance@ndrsmart.com.",
  } as const,
} as const;

export type ManagementProfile = {
  name: string;
  role?: string;
  photo?: string;
  bio?: string;
};

/**
 * Vertical 02 — management. Follows the About Us leadership interaction
 * (subtle hover/focus highlight + small description reveal). Five profile
 * slots ship as placeholders until the client supplies the records.
 */
export const verticalManagement = {
  heading: "Meet the Management",
  placeholderTitle: "Management profile",
  placeholderStatus: "Official profile pending",
  placeholderNote: "Name, designation and biography to be confirmed.",
  profiles: [] as readonly ManagementProfile[],
  placeholderSlots: 5,
} as const;

export type LifecycleStageImage = {
  src: string;
  alt: string;
  credit: string;
  width: number;
  height: number;
};

export type LifecycleStage = {
  index: string;
  title: string;
  body: string;
  image: LifecycleStageImage;
};

/**
 * Vertical 02 subpage — Development Lifecycle. The eight stage copies are
 * frozen editorial text (client-confirmed). Images are illustrative,
 * licensed photographs from Wikimedia Commons, clearly credited and not
 * depicting NDR sites. They are bundled locally under /images/lifecycle so
 * the static export never depends on a third-party DNS/network at runtime.
 */
export const vertical02DevelopmentLifecycle = {
  intro: {
    heading: "From site to asset. Documented stage by stage.",
    description:
      "How a piece of land becomes an operating asset — from land identification through due diligence, acquisition, approvals, design, construction and handover. Each stage below records the standard the manual holds every project to.",
  },
  stages: [
    {
      index: "01",
      title: "Land Identification",
      body: "Identifying strategic locations aligned with tenant requirements, market demand, and growth opportunities.",
      image: {
        src: "/images/lifecycle/01-land-identification.jpg",
        alt: "Green paddy fields in Andhra Pradesh, India",
        credit: "Image: Saishna96 / Wikimedia Commons, CC BY-SA 4.0",
        width: 1920,
        height: 1280,
      },
    },
    {
      index: "02",
      title: "Comprehensive Due Diligence",
      body: "Evaluating financial, local, legal, and environmental aspects to ensure land suitability and development viability.",
      image: {
        src: "/images/lifecycle/02-due-diligence.jpg",
        alt: "Signed contract documents and a pen",
        credit: "Image: Blogtrepreneur / Wikimedia Commons, CC BY 2.0",
        width: 1920,
        height: 1440,
      },
    },
    {
      index: "03",
      title: "Land Acquisition & SPV Structuring",
      body: "Securing suitable land through strategic lease or purchase arrangements and structuring the development through a dedicated Special Purpose Vehicle (SPV).",
      image: {
        src: "/images/lifecycle/03-land-acquisition.jpg",
        alt: "Business people at a boardroom dialogue session",
        credit: "Image: Richter Frank-Jurgen / Wikimedia Commons, CC BY 2.0",
        width: 1920,
        height: 1278,
      },
    },
    {
      index: "04",
      title: "Regulatory & Compliance Management",
      body: "Managing statutory approvals, regulatory requirements, and coordination with relevant authorities for seamless project progression.",
      image: {
        src: "/images/lifecycle/04-regulatory-compliance.jpg",
        alt: "Office time stamp and ink pad on a desk",
        credit: "Image: Jiří Sedláček (Frettie) / Wikimedia Commons, CC BY 3.0",
        width: 1920,
        height: 1280,
      },
    },
    {
      index: "05",
      title: "Project Planning & Design",
      body: "Transforming identified land into development-ready warehouse designs through technical studies, planning, approvals, and integrated engineering.",
      image: {
        src: "/images/lifecycle/05-project-planning.jpg",
        alt: "Architectural blueprint drawing of a building elevation",
        credit: "Image: Daderot / Wikimedia Commons, public domain",
        width: 1920,
        height: 1280,
      },
    },
    {
      index: "06",
      title: "Integrated Engineering Services",
      body: "Executing warehouse construction with strong oversight of quality, cost, timelines, and technical standards.",
      image: {
        src: "/images/lifecycle/06-engineering.jpg",
        alt: "Tower crane at a building construction site",
        credit: "Image: Taichung City Government / Wikimedia Commons, attribution",
        width: 1920,
        height: 1280,
      },
    },
    {
      index: "07",
      title: "Safety, Security & Risk Management",
      body: "Implementing robust security, safety, and compliance measures to protect people, assets, and operations.",
      image: {
        src: "/images/lifecycle/07-safety-risk.jpg",
        alt: "Orange construction area and hard hat safety signs",
        credit: "Image: The Navigators / Wikimedia Commons, CC0",
        width: 1920,
        height: 1280,
      },
    },
    {
      index: "08",
      title: "Asset Handover & Operations",
      body: "Preparing the completed warehouse for seamless handover and efficient day-to-day operations.",
      image: {
        src: "/images/lifecycle/08-asset-handover.jpg",
        alt: "Interior of a warehouse with pallet racking",
        credit: "Image: Axisadman / Wikimedia Commons, CC BY-SA 3.0",
        width: 1920,
        height: 1496,
      },
    },
  ] as const satisfies readonly LifecycleStage[],
  source: "Source: Client IA response · Post-Demerger business note",
} as const;

export type DevelopmentProcessStage = { index: string; title: string };

/**
 * Vertical 03 — From Land to Community. The four-stage residential
 * development process. Stage titles are approved content; no descriptive
 * copy is authored alongside them.
 */
export const vertical03DevelopmentProcess = {
  eyebrow: "Residential Development",
  heading: "From Land to Community",
  stages: [
    { index: "01", title: "Identify Land" },
    { index: "02", title: "Plan the Project" },
    { index: "03", title: "Develop and Deliver" },
    { index: "04", title: "Create a Community" },
  ] as const satisfies ReadonlyArray<DevelopmentProcessStage>,
} as const;

export type ResidentialValue = { index: string; title: string };

/**
 * Vertical 03 — What Defines Our Developments. The five approved values.
 * Each value is rendered as part of a single development system; no
 * descriptive copy is authored beyond the approved value titles.
 */
export const vertical03Values = {
  eyebrow: "Ave Acres Residential",
  heading: "What Defines Our Developments",
  values: [
    { index: "01", title: "Strategic Locations" },
    { index: "02", title: "Thoughtful Planning" },
    { index: "03", title: "Quality Infrastructure" },
    { index: "04", title: "Growth Potential" },
    { index: "05", title: "Responsible Development" },
  ] as const satisfies ReadonlyArray<ResidentialValue>,
} as const;

/**
 * Vertical 03 — closing panel linking to the Ave Acres residential platform.
 */
export const aveAcresClosing = {
  eyebrow: "Ave Acres Platform",
  heading: "Explore Our Residential Projects",
  description:
    "Discover our portfolio of residential plotted developments, locations, available plots, amenities, and project details on our dedicated residential platform.",
  cta: { label: "Explore Ave Acres", href: "https://aveacres.com/" },
} as const;
