import { contactDirectory as cmsDirectory } from "./generated/contactDirectory";
import { corporateSettings as cmsCorporate } from "./generated/corporateSettings";
import { locations as cmsLocations } from "./generated/locations";
import { INDIA_OUTLINE, MAP_VIEWBOX } from "./portfolio";

/**
 * Contact — NDR Smart Spaces.
 *
 * The company's contact record: where it is reached, how enquiries are routed
 * and which desk answers. Content is source-grounded — office addresses and
 * email addresses are approved records. Phone numbers and office hours are
 * draft particulars awaiting client confirmation before go-live; the directory
 * note restates the rule.
 *
 * Phase 2B — the office directory flows from the CMS-managed
 * `contact-directory` collection (regenerated byte-identically into
 * `./generated/contactDirectory`), the map directions from `corporate-settings`
 * and the map marker placement from the `locations` contact offset. Editorial
 * copy that has no CMS counterpart — the masthead heading, directory and form
 * copy — stays frozen.
 */

/* masthead ---------------------------------------------------------------- */

export const contactMasthead = {
  publication: "Contact",
  title: { before: "Contact ", accent: "NDR Smart Spaces" },
  statement:
    "Smart Spaces, HR and Grievance — the desks that answer your enquiry.",
} as const;

/* office directory -------------------------------------------------------- */

export type ContactOffice = {
  key: string;
  kind: string;
  name: string;
  lines: readonly string[];
  phone: string;
  email: { label: string; href: string };
  hours: string;
  directions?: { label: string; href: string; external: boolean };
};

const cmsOffices: readonly ContactOffice[] = cmsDirectory.map((entry) => ({
  key: entry.key,
  kind: entry.kind,
  name: entry.name,
  lines: entry.lines.map((line) => line.value),
  phone: entry.phone,
  email: { label: entry.email.label, href: entry.email.href },
  hours: entry.hours,
  ...("directions" in entry
    ? { directions: entry.directions as { label: string; href: string; external: boolean } }
    : {}),
}));

export const officeDirectory = {
  eyebrow: "Office directory",
  heading: "Where to reach us.",
  lede: "Three desks that receive correspondence — Smart Spaces, Human Resources, and Grievance Redressal.",
  note: "Phone numbers and office hours are draft particulars awaiting client confirmation before go-live. Hours are Indian Standard Time (IST).",
  offices: cmsOffices,
} as const;

/* inquiry routing --------------------------------------------------------- */

export type InquiryDesk = {
  key: "business" | "investor" | "media" | "esg" | "general";
  label: string;
  route: string;
  recipient: string;
  href: string;
  phone: string;
  response: string;
};

export const inquiryRouting = {
  eyebrow: "Routing",
  heading: "Contact the right team.",
  lede: "Every enquiry lands on the desk that answers it — business, investor relations, media, ESG or general. Write to the desk directly or use the enquiry form and the routing is applied for you.",
  note: "A misdirected enquiry is still answered within two business days.",
  desks: [
    {
      key: "business",
      label: "Business",
      route: "Grade A Warehousing · Asset Management · Land & Plotting · Partnerships",
      recipient: "project@ndrsmart.com",
      href: "mailto:project@ndrsmart.com",
      phone: "+91 44 4296 1203",
      response: "Within 2 business days",
    },
    {
      key: "investor",
      label: "Investor relations",
      route: "Investor centre · reports & disclosures · investor queries",
      recipient: "compliance@ndrsmart.com",
      href: "mailto:compliance@ndrsmart.com",
      phone: "+91 44 4296 1202",
      response: "Within 2 business days",
    },
    {
      key: "media",
      label: "Media",
      route: "Press releases · coverage · interviews",
      recipient: "compliance@ndrsmart.com",
      href: "mailto:compliance@ndrsmart.com",
      phone: "+91 44 4296 1204",
      response: "Within 2 business days",
    },
    {
      key: "esg",
      label: "ESG & sustainability",
      route: "Sustainability · ESG disclosures · climate",
      recipient: "compliance@ndrsmart.com",
      href: "mailto:compliance@ndrsmart.com",
      phone: "+91 44 4296 1205",
      response: "Within 2 business days",
    },
    {
      key: "general",
      label: "General",
      route: "Enquiries not covered by the desks above",
      recipient: "project@ndrsmart.com",
      href: "mailto:project@ndrsmart.com",
      phone: "+91 44 4296 1200",
      response: "Within 2 business days",
    },
  ] as readonly InquiryDesk[],
} as const;

/* form -------------------------------------------------------------------- */

export const correspondenceForm = {
  eyebrow: "Send an enquiry",
  heading: "Business Enquiry",
  subheading:
    "Tell us who you are and what you need — the enquiry is routed to the desk that answers it.",
  response: "Within 2 business days",
  note: "Enquiries are logged on intake, routed to the desk that answers them, and replied to within two business days.",
  fields: [
    { name: "name", label: "Name", type: "text", autocomplete: "name", required: true },
    {
      name: "company",
      label: "Company",
      type: "text",
      autocomplete: "organization",
      required: true,
    },
    { name: "email", label: "Work email", type: "email", autocomplete: "email", required: true },
    { name: "phone", label: "Phone", type: "tel", autocomplete: "tel", required: false },
  ] as const,
  enquiryTypes: [
    "Business enquiry",
    "Investor relations",
    "Press & media",
    "ESG & sustainability",
    "General",
  ] as const,
  messageLabel: "Message",
  submit: "Send Inquiry",
  sending: "Sending…",
  success: "Thank you — your enquiry has been sent and routed to the right desk.",
  route: {
    "Business enquiry": "project@ndrsmart.com",
    "Investor relations": "compliance@ndrsmart.com",
    "Press & media": "compliance@ndrsmart.com",
    "ESG & sustainability": "compliance@ndrsmart.com",
    General: "project@ndrsmart.com",
  } as const,
  deskForType: {
    "Business enquiry": "Business desk",
    "Investor relations": "Investor relations desk",
    "Press & media": "Media desk",
    "ESG & sustainability": "ESG desk",
    General: "General desk",
  } as const,
} as const;

/* map --------------------------------------------------------------------- */

const chennaiHq = cmsLocations.find((location) => location.id === "chennai-hq");
const chennaiContactOffset =
  chennaiHq !== undefined && "contactOffset" in chennaiHq ? chennaiHq.contactOffset : undefined;

export const contactMap = {
  eyebrow: "Office locations",
  heading: "The office on the map.",
  lede: "The corporate office in Chennai — the company's primary correspondence address — plotted on the group's schematic outline of India.",
  frameMark: "NDR Smart Spaces",
  plateRef: "Office locations",
  notToScale: "Schematic outline · not to scale",
  directions: {
    label: "Get directions",
    href: cmsCorporate.externalLinks.googleMapsDirectionsUrl,
  },
  source: "Source: Corporate office record",
  mapViewbox: MAP_VIEWBOX,
  indiaOutline: INDIA_OUTLINE,
  markers: [
    {
      id: "chennai-office",
      name: "Corporate office",
      place: "Chennai",
      region: "Tamil Nadu",
      lat: 13.0521,
      lon: 80.2461,
      x: chennaiContactOffset?.x ?? 384,
      y: chennaiContactOffset?.y ?? 828,
    },
  ] as readonly {
    id: string;
    name: string;
    place: string;
    region: string;
    lat: number;
    lon: number;
    x: number;
    y: number;
  }[],
} as const;

/* closing ----------------------------------------------------------------- */

export const contactClosing = {
  eyebrow: "Contact",
  line: "Contact NDR Smart Spaces.",
  body: "Smart Spaces, HR and Grievance enquiries.",
  primaryCta: { label: "Send an enquiry", href: "/en/contact#business-enquiry" },
} as const;
