import { media as cmsMedia } from "./generated/media";
import { publicationSettings as cmsPublication } from "./generated/publicationSettings";
import { corporateSettings as cmsCorporate } from "./generated/corporateSettings";
import { contactDirectory as cmsDirectory } from "./generated/contactDirectory";

export type PressCategory = "press-release" | "coverage" | "interview" | "update";

/**
 * Media — The Press Register.
 * Fifth major NDR editorial publication.
 *
 * The company's newsroom archive: releases, coverage, interviews and updates,
 * dated and referenced as a public record. Content is source-grounded. Nothing
 * here is invented — every entry is either an approved record or a clearly
 * marked draft awaiting client confirmation before go-live.
 *
 * Draft convention (inherited from the Investor Centre): periods flagged with
 * * are client-confirm. Provenance banners restate the rule.
 *
 * Phase 2B — the media kit, the press archive, the edition block, the
 * publication reference, the press contact and the register codes flow from
 * the CMS-managed `media`, `publication-settings`, `corporate-settings` and
 * `contact-directory` collections (regenerated byte-identically into
 * `./generated/*`). The press archive entries also live in the `media`
 * collection under the `press-archive` folder (seeded from
 * `PRESS_ARCHIVE_ENTRIES` below); the runtime `pressArchive.entries` derives
 * from the collection and the parity layer verifies the two are byte-equal.
 * Editorial copy that has no CMS counterpart — masthead and statement copy,
 * the featured spread, register notes and desk labels — stays frozen.
 */

export const MEDIA_EDITION = {
  asOn: cmsPublication.asOnDate,
  edition: `Edition ${cmsPublication.editionPeriod} · Volume I`,
} as const;

/**
 * Document-level publication reference. Every sheet in the register carries
 * this code in its folio line.
 */
export const MEDIA_PUBLICATION = {
  ref: `NDR-PR-${cmsPublication.editionPeriod}`,
  title: "The Press Register",
  classification: "Public record",
} as const;

export type MediaRecordStatus = "published" | "pending" | "draft";

export const MEDIA_STATUS_LABELS: Record<MediaRecordStatus, string> = {
  published: "On record",
  pending: "Pending filing",
  draft: "Draft for confirmation",
};

export const MEDIA_STATUS_TONES: Record<MediaRecordStatus, "active" | "pending"> = {
  published: "active",
  pending: "pending",
  draft: "pending",
};

/* press archive — seed source -------------------------------------------------- */

export type PressArchiveEntry = {
  id: string;
  ref: string;
  date: string;
  category: PressCategory;
  title: string;
  note?: string;
  publication?: string;
  image?: string;
  status: MediaRecordStatus;
  href?: string;
  external?: boolean;
};

/**
 * The frozen press archive source. The `media` collection seeds one record per
 * entry (folder `press-archive`, collection status `pending`, editorial status
 * carried in `recordStatus`); `pressArchive.entries` derives from the
 * collection and `verify:parity` asserts the two stay byte-equal.
 */
export const PRESS_ARCHIVE_ENTRIES: readonly PressArchiveEntry[] = [
  {
    id: "cv-001",
    ref: "CV-001",
    date: "9 June 2026",
    category: "coverage",
    title: "NDR opens warehouse",
    note: "Coverage of the Kongara Kalan, Hyderabad warehouse inauguration.",
    publication: "The Hans India",
    image: "/images/media/coverage-04.jpg",
    status: "published",
  },
  {
    id: "cv-002",
    ref: "CV-002",
    date: "9 June 2026",
    category: "coverage",
    title: "NDR Smart Spaces inaugurates facility at Kongara Kalan",
    note: "Coverage of the Kongara Kalan, Hyderabad warehouse inauguration.",
    publication: "New Indian Express",
    status: "published",
  },
  {
    id: "cv-003",
    ref: "CV-003",
    date: "10 June 2026",
    category: "coverage",
    title: "NDR Smart Spaces inaugurates facility at Kongara Kalan",
    note: "Coverage of the Kongara Kalan, Hyderabad warehouse inauguration.",
    publication: "Telangana Today",
    image: "/images/media/coverage-05.jpg",
    status: "published",
  },
  {
    id: "cv-004",
    ref: "CV-004",
    date: "10 June 2026",
    category: "coverage",
    title: "Warehousing Facility",
    note: "Coverage of the Kongara Kalan, Hyderabad warehouse inauguration.",
    publication: "The Pioneer",
    image: "/images/media/coverage-06.jpg",
    status: "published",
  },
  {
    id: "cv-005",
    ref: "CV-005",
    date: "10 June 2026",
    category: "coverage",
    title: "NDR Smart Spaces inaugurates 0.6 million sq feet facility at Kongara Kalan, Hyderabad",
    note: "Coverage of the Kongara Kalan, Hyderabad warehouse inauguration.",
    publication: "The Pioneer",
    status: "published",
  },
  {
    id: "cv-006",
    ref: "CV-006",
    date: "10 June 2026",
    category: "coverage",
    title: "NDR Smart Spaces inaugurates ~0.6 million sq ft facility at Kongara Kalan, Hyderabad",
    note: "Coverage of the Kongara Kalan, Hyderabad warehouse inauguration.",
    publication: "Andhra Prabha",
    image: "/images/media/coverage-01.jpg",
    status: "published",
  },
  {
    id: "cv-007",
    ref: "CV-007",
    date: "10 June 2026*",
    category: "coverage",
    title: "NDR Smart Spaces launches new warehousing facility",
    note: "Coverage of the Kongara Kalan, Hyderabad warehouse inauguration. Headline translated from Telugu — pending client confirmation.",
    publication: "South India Times",
    image: "/images/media/coverage-07.jpg",
    status: "draft",
  },
  {
    id: "cv-008",
    ref: "CV-008",
    date: "10 June 2026",
    category: "coverage",
    title: "NDR Smart Spaces inaugurates ~0.6 million sq ft facility at Kongara Kalan, Hyderabad",
    note: "Coverage of the Kongara Kalan, Hyderabad warehouse inauguration.",
    publication: "Surya",
    image: "/images/media/coverage-08.jpg",
    status: "published",
  },
  {
    id: "cv-009",
    ref: "CV-009",
    date: "10 June 2026*",
    category: "coverage",
    title: "NDR Smart Spaces opens new warehouse",
    note: "Coverage of the Kongara Kalan, Hyderabad warehouse inauguration. Headline translated from Telugu — pending client confirmation.",
    publication: "Nava Telangana (print)",
    image: "/images/media/coverage-02.jpg",
    status: "draft",
  },
  {
    id: "cv-010",
    ref: "CV-010",
    date: "10 June 2026*",
    category: "coverage",
    title: "NDR launches large warehouse at Kongara Kalan",
    note: "Coverage of the Kongara Kalan, Hyderabad warehouse inauguration. Headline translated from Telugu — pending client confirmation.",
    publication: "Praja Sakti",
    image: "/images/media/coverage-03.jpg",
    status: "draft",
  },
  {
    id: "cv-011",
    ref: "CV-011",
    date: "8 June 2026",
    category: "coverage",
    title: "NDR Smart Spaces opens 0.6 Mn Sq Ft hub in Hyderabad",
    note: "Coverage of the Kongara Kalan, Hyderabad warehouse inauguration.",
    publication: "Manufacturing Today India",
    status: "published",
    href: "https://www.manufacturingtodayindia.com/ndr-smart-spaces-opens-in-hyderabad",
    external: true,
  },
  {
    id: "cv-012",
    ref: "CV-012",
    date: "8 June 2026",
    category: "coverage",
    title:
      "NDR Smart Spaces Inaugurates ~0.6 Million Sq Ft Grade A Warehousing Facility at Kongara Kalan, Hyderabad",
    note: "Coverage of the Kongara Kalan, Hyderabad warehouse inauguration.",
    publication: "Telugu Times",
    status: "published",
    href: "https://www.telugutimes.net/en/politics/navyandhra/ndr-smart-spaces-inaugurates-0-6-million-sq-ft-grade-a-warehousing-facility-at-kongara-kalan-hyderabad-348198.html",
    external: true,
  },
  {
    id: "cv-013",
    ref: "CV-013",
    date: "9 June 2026*",
    category: "coverage",
    title: "NDR Smart Spaces opens 0.6 million sq ft facility",
    note: "Coverage of the Kongara Kalan, Hyderabad warehouse inauguration. Headline translated from Telugu — pending client confirmation.",
    publication: "Nava Telangana (online)",
    status: "draft",
    href: "https://navatelangana.com/ndr-smart-spaces-opens-0-6-million-sq-ft-facility/",
    external: true,
  },
  {
    id: "cv-014",
    ref: "CV-014",
    date: "9 June 2026*",
    category: "coverage",
    title:
      "NDR Smart Spaces launches approximately 0.6 million sq ft facility at Kongara Kalan, Hyderabad",
    note: "Coverage of the Kongara Kalan, Hyderabad warehouse inauguration. Headline translated from Telugu — pending client confirmation.",
    publication: "Daily Hunt",
    status: "draft",
    href: "https://m.dailyhunt.in/news/india/telugu/pvrnews-epaper-dh4fcab02e50334d6f8a069dbf5eaa5131/haidaraabaadloni+kongara+kalaanlo+sumaaru+06+miliyan+chadarapu+adugula+sadupaayaanni+praarambhinchina+endiaar+smaart+speses-newsid-dh4fcab02e50334d6f8a069dbf5eaa5131_d51cedd0642011f1b6b72f9b905a4ba2?sm=Y",
    external: true,
  },
];

/* masthead ---------------------------------------------------------------- */

export const mediaMasthead = {
  registry: cmsCorporate.registryLine,
  publication: "NDR Press Register",
  section: "Media & Newsroom",
  title: { before: "The ", accent: "Media Highlights", after: "" },
  statement:
    "The company's newsroom archive — releases, coverage, interviews and updates, dated and referenced as a public record.",
  asOn: MEDIA_EDITION.asOn,
  edition: MEDIA_EDITION.edition,
  folio: `Register ${cmsPublication.editionPeriod}`,
  controlCaption: "REF CV-001 · COVER",
  watermark: "PR",
} as const;

/* statement --------------------------------------------------------------- */

export const mediaStatement = {
  eyebrow: "The editorial statement",
  heading: "A newsroom archive, kept as a public record.",
  statement:
    "This register records how NDR Smart Spaces speaks to the public — the releases it issues, the coverage it receives and the updates it files. Every entry carries a date and a reference; nothing is stated that is not on record.",
  signatory: "NDR Smart Spaces · Media Desk",
  provenance:
    "Entries in this register marked * are placeholders pending confirmation against the approved newsroom record.",
  reference: `${MEDIA_PUBLICATION.ref} · Statement`,
  recorded: `Recorded · ${cmsPublication.editionPeriod}`,
} as const;

/* generated media read model --------------------------------------------- */

/**
 * Widened view over the generated media module. The generated union covers the
 * media-kit records today and grows with the press-archive records the CMS
 * seeds; the derivation below reads either shape without depending on the
 * current on-disk export.
 */
type CmsMediaRecord = {
  id: string;
  status: string;
  folder: string;
  ref?: string;
  label?: string;
  caption?: string;
  format?: string;
  classification?: string;
  revision?: string;
  date?: string;
  category?: string;
  recordStatus?: string;
  publication?: string;
  image?: string;
  href?: string;
  external?: boolean;
};

const cmsMediaRecords = cmsMedia as unknown as readonly CmsMediaRecord[];

/* press archive ----------------------------------------------------------- */

export const PRESS_CATEGORIES: readonly {
  key: PressCategory;
  label: string;
  description: string;
}[] = [
  {
    key: "press-release",
    label: "Press Releases",
    description: "Statements issued by the company.",
  },
  {
    key: "coverage",
    label: "Coverage",
    description: "Reporting and mentions by external publications.",
  },
  {
    key: "interview",
    label: "Interviews",
    description: "Interviews given by leadership.",
  },
  {
    key: "update",
    label: "Updates",
    description: "Programmatic updates to the record.",
  },
];

const cmsPressEntries: readonly PressArchiveEntry[] = (() => {
  const result: PressArchiveEntry[] = [];
  for (const record of cmsMediaRecords) {
    if (record.folder !== "press-archive") continue;
    result.push({
      id: record.id,
      ref: record.ref ?? "",
      date: record.date ?? "",
      category: (record.category ?? "update") as PressCategory,
      title: record.label ?? "",
      ...(typeof record.caption === "string" ? { note: record.caption } : {}),
      ...(typeof record.publication === "string" ? { publication: record.publication } : {}),
      ...(typeof record.image === "string" ? { image: record.image } : {}),
      status: (record.recordStatus as MediaRecordStatus) ?? "draft",
      ...(typeof record.href === "string" ? { href: record.href } : {}),
      ...(record.external === true ? { external: true } : {}),
    });
  }
  return result;
})();

export const pressArchive = {
  eyebrow: "The archive",
  heading: "The public record, dated and referenced.",
  lede: "Releases, coverage, interviews and updates filed by the company — each entry with its date and reference. The archive is being filed; entries publish as approvals land.",
  note: "The archive is being filed. Entries publish as they are approved.",
  registerCode: `${MEDIA_PUBLICATION.ref} · Press archive`,
  folio: "Folio PR",
  categories: PRESS_CATEGORIES,
  entries: cmsPressEntries,
} as const;

/* media kit --------------------------------------------------------------- */

export type MediaKitItemStatus = "available" | "pending";

export type MediaKitItem = {
  ref: string;
  label: string;
  note: string;
  format: string;
  classification: string;
  revision: string;
  status: MediaKitItemStatus;
};

const cmsMediaKit: readonly MediaKitItem[] = (() => {
  const result: MediaKitItem[] = [];
  for (const record of cmsMediaRecords) {
    if (record.folder !== "media-kit") continue;
    result.push({
      ref: record.ref ?? "",
      label: record.label ?? "",
      note: record.caption ?? "",
      format: record.format ?? "",
      classification: record.classification ?? "",
      revision: record.revision ?? "",
      status: record.status as MediaKitItemStatus,
    });
  }
  return result;
})();

export const mediaKit = {
  eyebrow: "Media kit",
  heading: "Assets for the press.",
  lede: "The official materials of the company — profile, logos and brand guidance — filed for editorial use.",
  note: "Kit assets publish as the brand system is approved.",
  registerCode: `${MEDIA_PUBLICATION.ref} · Asset register`,
  items: cmsMediaKit,
} as const;

/* press contact ----------------------------------------------------------- */

const pressEmail =
  cmsCorporate.emails.find((e) => e.value === "compliance@ndrsmart.com") ?? cmsCorporate.emails[0];
const businessEmail =
  cmsCorporate.emails.find((e) => e.value === "project@ndrsmart.com") ?? cmsCorporate.emails[1];

export const pressContact = {
  eyebrow: "Press contact",
  heading: "Write to the correspondence office.",
  body: "Journalists and editors: direct press enquiries to the press desk below. Every enquiry is logged, routed and answered within two business days.",
  response: {
    label: "Response",
    value: cmsCorporate.pressResponseExpectation,
    classification: "Standard response",
  },
  registerCode: `${MEDIA_PUBLICATION.ref} · Correspondence`,
  departments: [
    {
      ref: "PC-01",
      label: "Press desk",
      value: pressEmail.value,
      href: `mailto:${pressEmail.value}`,
      note: "Releases, coverage and interviews — the newsroom register.",
    },
    {
      ref: "PC-02",
      label: "Business desk",
      value: businessEmail.value,
      href: `mailto:${businessEmail.value}`,
      note: "Business enquiries, partnerships and the commercial line.",
    },
  ],
  address: cmsCorporate.addresses[0].lines.map((line) => line.value).join(", "),
} as const;

/* closing ----------------------------------------------------------------- */

export const mediaClosing = {
  eyebrow: "Register · Endnote",
  line: "The register remains open.",
  body: "The company's public record is kept in order — releases, coverage, interviews and updates file as they are approved. Until then, every entry carries its status.",
  publicationRef: MEDIA_PUBLICATION.ref,
  edition: MEDIA_EDITION.edition,
  primaryCta: { label: "Write to the press desk", href: "mailto:compliance@ndrsmart.com" },
  secondaryCta: { label: "Contact NDR Smart Spaces.", href: "/en/contact" },
  tertiaryLink: { label: "NDR InvIT Trust", href: "https://ndrinvit.com" },
  enquiry: { label: "Business Enquiry", href: "/en/contact#business-enquiry" },
  provenanceNote:
    "Draft entries in this register are marked * and remain subject to client confirmation before go-live.",
} as const;
