/**
 * Header & footer navigation.
 *
 * Phase 2B — the navigation record flows from the CMS-managed `navigation`
 * collection (regenerated byte-identically into `./generated/navigation`).
 * The item types and the active-path helper stay frozen.
 */

import { navigation as cmsNavigation } from "./generated/navigation";

export type MenuLink = {
  label: string;
  href: string;
  external?: boolean;
};

export type MegaMenuColumn = {
  heading: string;
  links: readonly MenuLink[];
};

export type MenuOverview = {
  label: string;
  tagline: string;
  href: string;
};

export type MenuId = "business" | "investor";

export type NavMenu = {
  type: "menu";
  id: MenuId;
  label: string;
  href: string;
  align: "left" | "right";
  overview: MenuOverview;
  columns: readonly MegaMenuColumn[];
};

export type NavLink = {
  type: "link";
  label: string;
  href: string;
};

export type NavItem = NavLink | NavMenu;

export const utilityStrip = cmsNavigation.utilityStrip;

export const headerCta = cmsNavigation.headerCta;

export const navItems: readonly NavItem[] = cmsNavigation.navItems;

export const mobileNavItems: readonly NavItem[] = cmsNavigation.mobileNavItems;

export const mobileMenuFooter = cmsNavigation.mobileMenuFooter;

export const siteHome: string = cmsNavigation.siteHome;

export function isActivePath(pathname: string, href: string): boolean {
  if (href === "#") return false;
  if (href.startsWith("mailto:") || href.startsWith("https://")) return false;
  const clean = href.split("#")[0];
  if (clean === "/en") return pathname === "/en";
  return pathname === clean || pathname.startsWith(clean + "/");
}
